### ISSUE TITLE
[BUG] Request Entity Too Large 

### ISSUE THREAD

**Issue by shiquanyang** [marqo-ai/marqo#62]
**Describe the bug**
I am using the image-to-image search mode. During the "add_documents" process, marqo throws out an error message which says "HTTPError: 413 Client Error: Request Entity Too Large for url: http://localhost:8882/indexes/duplicate-detection-index/documents?refresh=true&device=cpu". I use 10,000 images to build the index. Is there a limit on the number of images? Or it's something else caused the problem? What can I do to fix this issue? Thanks. 

**Expected behavior**
Use the provided 10,000 images to build the index, and find similar images for the query images.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chrome]

**Comment by jn2clark** [comment]
Thanks @shiquanyang! I think this should be resolved by using batching. With the add_documents command you can pass through a batch_size argument which will send many requests instead of one. 
E.g
```
mq.client(index_name).add_documents(documents, batch_size=50)
```
You can also use multiple processes for faster indexing;
```
mq.client(index_name).add_documents(documents, batch_size=50, processes=2)
```
To get it to work with a GPU machine, you need to add one more flag to the run command (--gpus all, detailed here https://marqo.pages.dev/using_marqo_with_a_gpu/). The device can then be selected as well (default is CPU)
```
mq.client(index_name).add_documents(documents, batch_size=50, processes=2, device='cuda')
```
For multiple gpus, the processes will be split evenly amongst them, i.e. 
4 GPU's and processes=4 -> 1 process/GPU, 
4 GPU's and processes=8 -> 2 process/GPU, 
Let me know if this does not work.

**Comment by shiquanyang** [comment]
Thanks for the prompt response! I've tried setting the two parameters (batch_size and processes) in the add_documents API call, the problem is resolved now. Thanks!
