### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Arseniy-II** [marqo-ai/marqo#820]
**Describe the bug**
Docker images freeze on Amazon Linux 2023 AMI (with 30 Gb of space) for marqo:2.0.0 and marqo:latest

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to AWS
2. Lunch EC2 t2 micro instance with Amazon Linux 2023 AMI 
3. SSH into instance
4. Install docker and try to run marqo:2.0.0 or marqo:latest

**Expected behaviour**
Vector database up and running

**Actual result**
Stoped at step "Marqo is deploying the application and waiting for the response from document API to start..." and nothing is happening for 3 hours

**Screenshots**

**Desktop (please complete the following information):**
 - OS: AWS Linux 2023 AMI 
 - Docker image Version 2.0.0 and latest

**Additional context**
![Screenshot 2024-04-24 at 14 41 29](https://github.com/marqo-ai/marqo/assets/22207770/0aaff787-4b58-4eae-91bb-3e5a6c56a598)
![Screenshot 2024-04-24 at 14 42 00](https://github.com/marqo-ai/marqo/assets/22207770/5b93cbdf-4c09-4325-966e-6bf8c044ac4a)

**Comment by tomhamer** [comment]
Hey Arseniy, thanks for reaching out. The absolute minimum amount of RAM you can use to run marqo is 8GB. We have a ticket out so that marqo will have a more helpful error in this case: https://github.com/marqo-ai/marqo/issues/796

The least expensive instance you can use to run marqo is an r7g.medium, but I would recommend a g4dn.xlarge for the best performance. If you want to get this into production, the marqo kubernetes apps or marqo cloud are the best options.

https://github.com/marqo-ai/marqo-on-kubernetes

**Comment by Arseniy-II** [comment]
@tomhamer Thanks! I was able to lunch it without any issues on r7g.medium!
